name: CI - Master
on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'
            - name: Install dependencies
              run: npm install yarn && npm install
            - name: Lint and Tests 🔧
              run: yarn lint && yarn test-no-silent
            - name: Publish package on NPM 📦
              run: yarn build && yarn publish-beta
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}]
            - uses: codecov/codecov-action@v3
              with:
                token: ${{ secrets.CODE_COV_KEY }}
                verbose: true