name: CI - Master
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'
            - name: Install dependencies
              run: npm install yarn && npm install
            - name: Lint and Tests 🔧
              run: yarn lint && yarn test-no-silent
            - name: Building...
              run: yarn build
            - name: Publish package on NPM 📦
              run: node generate-version.js env=production && yarn publish-prod
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              if: github.event_name != 'pull_request'
            - uses: codecov/codecov-action@v3
              with:
                  token: ${{ secrets.CODE_COV_KEY }}
                  verbose: true
              if: github.event_name != 'pull_request'
